CREATE DATABASE IF NOT EXISTS flight_booking;
USE flight_booking;

CREATE TABLE IF NOT EXISTS users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 email VARCHAR(150) UNIQUE,
 password VARCHAR(255),
 role VARCHAR(20) DEFAULT 'USER',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flights(
 id INT AUTO_INCREMENT PRIMARY KEY,
 flight_no VARCHAR(20),
 source VARCHAR(50),
 destination VARCHAR(50),
 depart_time DATETIME,
 arrive_time DATETIME,
 price DECIMAL(10,2),
 aircraft_type VARCHAR(20) DEFAULT 'A320'
);

CREATE TABLE IF NOT EXISTS bookings(
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT,
 flight_id INT,
 booking_date DATETIME DEFAULT CURRENT_TIMESTAMP,
 cancel_status VARCHAR(20) DEFAULT 'ACTIVE',
 refund_status VARCHAR(20) DEFAULT 'NONE'
);

CREATE TABLE IF NOT EXISTS passengers(
 id INT AUTO_INCREMENT PRIMARY KEY,
 booking_id INT,
 name VARCHAR(100),
 age INT,
 gender VARCHAR(10),
 phone VARCHAR(20),
 ticket_no VARCHAR(50),
 cancel_status VARCHAR(20) DEFAULT 'ACTIVE',
 refund_status VARCHAR(20) DEFAULT 'NONE'
);

CREATE TABLE IF NOT EXISTS audit_log(
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NULL,
 role VARCHAR(20),
 action VARCHAR(255),
 details TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seats(
 id INT AUTO_INCREMENT PRIMARY KEY,
 flight_id INT NOT NULL,
 seat_no VARCHAR(10) NOT NULL,
 status ENUM('FREE','HELD','BOOKED') DEFAULT 'FREE',
 held_until DATETIME NULL,
 UNIQUE KEY seat_unique(flight_id, seat_no)
);
