pipeline {
    agent any

    environment {
        IMAGE = "anurajyellurkar/flight-booking"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/anurajyellurkar/devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('flight_booking_final16') {
                    sh "docker build -t $IMAGE:latest ."
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh "trivy image --severity HIGH,CRITICAL $IMAGE:latest"
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                    sh "docker push $IMAGE:latest"
                }
            }
        }

        stage('Deploy') {
            steps {
                sh """
                cd ~/devops/flight_booking_final16
                docker compose pull
                docker compose up -d
                """
            }
        }
    }
}
