pipeline {
    agent any

    environment {
        IMAGE = "anuraj2913/flight-booking"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/anurajyellurkar/devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('flight_booking_final16') {
                    sh "docker build -t $IMAGE:latest ."
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh "trivy image --severity HIGH,CRITICAL $IMAGE:latest"
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                    sh "docker push $IMAGE:latest"
                }
            }
        }

        stage('Deploy') {
    steps {
        sh """
        cd /var/lib/jenkins/workspace/flight-booking-pipeline/flight_booking_final16
        docker-compose pull
        docker-compose up -d
        """
    }
}


    }
}
