pipeline {
    agent any

    environment {
        IMAGE = "anuraj2913/flight-booking"
        CONTAINER = "flight-booking-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/anurajyellurkar/devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('flight_booking_final16') {
                    sh "docker build -t $IMAGE:latest ."
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh "trivy image --severity HIGH,CRITICAL --exit-code 0 $IMAGE:latest"
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                    sh "docker push $IMAGE:latest"
                }
            }
        }

        stage('Deploy') {
            steps {
                sh """
                # Pull latest image
                docker pull $IMAGE:latest

                # Stop old container if running
                docker rm -f $CONTAINER || true

                # Run container again
                docker run -d --name $CONTAINER -p 80:80 $IMAGE:latest
                """
            }
        }
    }
}
